parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: jobeet_test
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 41050a8a136595c7b4829fe9dcc51fdd41f036fd
    database_path: null
