<?php
/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser
{

    /**
     * @var integer $id
     */
    protected $id;
    
    /**
     *
     * @var type int
     */
    protected $site;

    /**
     * @var type int
     */
    private $accommodation;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }
    
    /**
     * {@inheritdoc}
     */
    public function setSite($site)
    {
        $this->site = $site;
    }

    /**
     * {@inheritdoc}
     */
    public function getSite()
    {
        return $this->site;
    }

    
    /**
     * Set accommodation
     *
     * @param \TNE\OperatorBundle\Entity\Accommodation $accommodation
     * @return User
     */
    public function setAccommodation(\TNE\OperatorBundle\Entity\Accommodation $accommodation = null)
    {
        $this->accommodation = $accommodation;
    
        return $this;
    }

    /**
     * Get accommodation
     *
     * @return \TNE\OperatorBundle\Entity\Accommodation 
     */
    public function getAccommodation()
    {
        return $this->accommodation;
    }


}