<?php

namespace Application\Sonata\PageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleMediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleMediaRepository extends EntityRepository
{
}
